#!/bin/sh

cd "`dirname "$0"`"
export SDL_DYNAMIC_API=libSDL2.so
export LD_LIBRARY_PATH="`pwd`/linux-bins/@@ARCH@@"
chmod 755 ./linux-bins/@@ARCH@@/@@BINARY_NAME@@
./linux-bins/@@ARCH@@/@@BINARY_NAME@@ -basedir . "$@"
