#!/bin/sh

cd "`dirname "$0"`"
if test -d ~/.nexuiz
then
	if test ! -d ~/.rexuiz
	then
		ln -fs .nexuiz ~/.rexuiz
	fi
fi
if test -z "$LD_LIBRARY_PATH"
then
	export LD_LIBRARY_PATH="`pwd`/linux-bins/@@ARCH@@"
else
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pwd`/linux-bins/@@ARCH@@"
fi
export SDL_DYNAMIC_API=libSDL2.so
chmod 755 ./linux-bins/@@ARCH@@/@@BINARY_NAME@@
exec ./linux-bins/@@ARCH@@/@@BINARY_NAME@@ -basedir . "$@"
